# Generated by Django 4.2.3 on 2023-08-12 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['is_read', 'created']},
        ),
    ]
